name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      build_api_docs: "ON"
    steps:
    - name: Checkout FLAMEGPU2/FLAMEGPU2-docs
      uses: actions/checkout@v2
      with:
        path: FLAMEGPU2-docs

    - name: Checkout FLAMEGPU2/FLAMEGPU2
      if: env.build_api_docs == 'ON'
      uses: actions/checkout@v2
      with:
        repository: FLAMEGPU/FLAMEGPU2
        path: FLAMEGPU2

    # Install dependencies via apt
    - name: Install graphviz
      run: sudo apt -y install graphviz 

    # Install API docs dependencies via apt
    - name: Install doxygen
      if: env.build_api_docs == 'ON'
      run: sudo apt -y install doxygen

    - name: Install python packages
      working-directory: FLAMEGPU2-docs
      run: |
        mkdir -p -m 700 .venv
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install -r requirements.txt

    - name: Configure
      working-directory: FLAMEGPU2-docs
      run: |
        source .venv/bin/activate
        cmake . -B build

    - name: Build
      working-directory: FLAMEGPU2-docs/build
      run: cmake --build . --target all --verbose -j `nproc`

    - name: Create Archive on PR
      if: ${{ github.event_name == 'pull_request' }}
      working-directory: FLAMEGPU2-docs/build
      run: zip html.zip -r userguide/ 

    - name: Upload Artifact on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        name: userguide
        path: FLAMEGPU2-docs/build/html.zip
        if-no-files-found: error
        retention-days: 14
